variables:
  - name: project_name
    default_value: '{{ file_name ffizer_dst_folder }}'
  - name: version
    default_value: "0.1.0-dev"
  - name: author
    default_value: '{{ env_var "USERNAME" }}'
  - name: description
    default_value: ""
  - name: gitignore_what
    default_value: rust,git,visualstudiocode
    ask: Create useful .gitignore (via gitignore.io) for

ignores:
  - target
  - .git/*
  - .git # exclude .git of the template host
  - README.md
  - COPYING

imports:
  - uri: "git@github.com:ffizer/templates_default.git"
    rev: "master"
    subfolder: "gitignore_io"
  - uri: "git@github.com:ffizer/templates_default.git"
    rev: "master"
    subfolder: "oss_license"